name: Tess Rethore Photography
favicon: null
layout_spectrum: 0.28852
typography_spectrum: 0.49411
title: Tess Rethore Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5e9dd0'
    - '#2a62ad'
    - '#0e0351'
    - '#fefefe'
    - '#d4d5d9'
  brandStrength: 0.4467018414288759
  lightness: 0.036048316629603505
  saturation: 0.9468139957170933
  rhythmicContrast: 0.9556527836248279
purpose: []
